-- BASELINE SNAPSHOT ONLY. NEVER APPLY TO THE EXISTING PRODUCTION PROJECT.
-- Read-only capture of foundational objects absent from migration history.
-- For a brand-new empty Supabase database, run before supabase/migrations.

create table public.app_locales (code text primary key, name text not null, sort_order integer not null default 0, is_active boolean not null default true);
create table public.customers (id uuid primary key default gen_random_uuid(), auth_user_id uuid unique references auth.users(id) on delete cascade, name text not null default 'Klient', phone text unique, qr_token uuid not null unique default gen_random_uuid(), points_balance numeric(10,2) not null default 0 check(points_balance>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.collections (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, icon text, description text, sort_order integer not null default 0, active boolean not null default true, created_at timestamptz not null default now());
create table public.collection_items (id uuid primary key default gen_random_uuid(), collection_id uuid not null references public.collections(id) on delete cascade, code text not null, name text not null, icon text, sort_order integer not null default 0, active boolean not null default true, unique(collection_id,code));
create table public.collection_rewards (id uuid primary key default gen_random_uuid(), collection_id uuid not null references public.collections(id) on delete cascade, unlock_count integer not null check(unlock_count>0), reward_code text not null, reward_name text not null, reward_description text, secret boolean not null default true, active boolean not null default true, unique(collection_id,reward_code));
create table public.purchases (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, amount_total numeric(10,2) not null check(amount_total>0), points_redeemed numeric(10,2) not null default 0 check(points_redeemed>=0), amount_paid numeric(10,2) not null check(amount_paid>=0), points_earned numeric(10,2) not null default 0 check(points_earned>=0), payment_method text not null check(payment_method=any(array['KARTA','GOTÓWKA','INNE'])), status text not null default 'COMPLETED' check(status=any(array['COMPLETED','CANCELLED'])), created_at timestamptz not null default now());
create table public.loyalty_transactions (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, purchase_id uuid references public.purchases(id) on delete set null, points_delta numeric(10,2) not null check(points_delta<>0), reason text not null check(reason=any(array['EARN','REDEEM','ADJUSTMENT'])), created_at timestamptz not null default now());
create table public.customer_collection_items (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, item_id uuid not null references public.collection_items(id) on delete cascade, purchase_id uuid references public.purchases(id) on delete set null, unlocked_at timestamptz not null default now(), unique(customer_id,item_id));
create table public.customer_rewards (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, collection_reward_id uuid not null references public.collection_rewards(id) on delete cascade, status text not null default 'AVAILABLE' check(status=any(array['AVAILABLE','REDEEMED','EXPIRED'])), earned_at timestamptz not null default now(), redeemed_at timestamptz, expires_at timestamptz, unique(customer_id,collection_reward_id));
create table public.menu_categories (id uuid primary key default gen_random_uuid(), slug text not null unique, icon text, image_url text, sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), visibility text not null default 'public' check(visibility=any(array['public','authenticated','unlocked','hidden'])), available_starts_at timestamptz, available_ends_at timestamptz, required_reward_id uuid references public.collection_rewards(id) on delete set null, check(available_starts_at is null or available_ends_at is null or available_ends_at>available_starts_at), check(visibility<>'unlocked' or required_reward_id is not null));
create table public.menu_category_translations (category_id uuid not null references public.menu_categories(id) on delete cascade, locale text not null references public.app_locales(code) on update cascade on delete restrict, name text not null, description text, primary key(category_id,locale));
create table public.menu_products (id uuid primary key default gen_random_uuid(), category_id uuid not null references public.menu_categories(id) on delete restrict, slug text not null unique, legacy_key text unique, image_url text, regular_price numeric(10,2) not null check(regular_price>=0), promo_price numeric(10,2), promo_starts_at timestamptz, promo_ends_at timestamptz, badge text, is_new boolean not null default false, new_until timestamptz, is_active boolean not null default true, is_available boolean not null default true, sort_order integer not null default 0, ice_cream_flavour_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), product_type text not null default 'standard' check(product_type=any(array['standard','ice_cream','reward','secret'])), visibility text not null default 'public' check(visibility=any(array['public','authenticated','unlocked','hidden'])), is_orderable boolean not null default true, available_starts_at timestamptz, available_ends_at timestamptz, required_reward_id uuid references public.collection_rewards(id) on delete set null, check(promo_price is null or promo_price>=0 and promo_price<=regular_price), check(promo_starts_at is null or promo_ends_at is null or promo_ends_at>promo_starts_at), check(available_starts_at is null or available_ends_at is null or available_ends_at>available_starts_at), check(visibility<>'unlocked' or required_reward_id is not null));
create table public.menu_product_translations (product_id uuid not null references public.menu_products(id) on delete cascade, locale text not null references public.app_locales(code) on update cascade on delete restrict, name text not null, description text, primary key(product_id,locale));

alter table public.app_locales enable row level security; alter table public.customers enable row level security;
alter table public.collections enable row level security; alter table public.collection_items enable row level security;
alter table public.collection_rewards enable row level security; alter table public.purchases enable row level security;
alter table public.loyalty_transactions enable row level security; alter table public.customer_collection_items enable row level security;
alter table public.customer_rewards enable row level security; alter table public.menu_categories enable row level security;
alter table public.menu_category_translations enable row level security; alter table public.menu_products enable row level security;
alter table public.menu_product_translations enable row level security;
insert into public.app_locales values ('pl','Polski',10,true),('de','Deutsch',20,true),('en','English',30,true),('cs','Čeština',40,true);

-- The live menu_products FK to ice_cream_flavours is intentionally deferred:
-- that table is created by migration 20260828214551. Add the FK after migrations.
