import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {filterOrders,nextAction,historyAction,isStale} from '../admin/admin-workflow.js';
import {createStorageAdapter,storagePathFromUrl} from '../admin/admin-storage.js';

const root=new URL('../',import.meta.url);
const read=path=>readFile(new URL(path,root),'utf8');

test('admin uses native editable login controls with no startup reload',async()=>{const [html,js,css]=await Promise.all([read('admin/index.html'),read('admin/admin.js'),read('admin/admin.css')]);assert.match(html,/input id="email"[^>]+type="email"/);assert.match(html,/input id="password"[^>]+type="password"/);assert.match(html,/id="loginForm"/);assert.doesNotMatch(js,/location\.reload\s*\(/);assert.doesNotMatch(css,/pointer-events\s*:\s*none[^}]*input/i)});
test('admin is isolated from customer service worker',async()=>{const [html,js,sw]=await Promise.all([read('admin/index.html'),read('admin/admin.js'),read('sw.js')]);assert.doesNotMatch(html+js,/serviceWorker\.register/);assert.match(sw,/pathname\.startsWith\('\/admin\/'\)/);assert.match(sw,/pathname === '\/admin'/)});
test('legacy staff routes use temporary redirects to admin',async()=>{const config=JSON.parse(await read('vercel.json'));const redirects=Object.fromEntries(config.redirects.map(rule=>[rule.source,rule]));for(const source of ['/staff','/staff/','/staff.html']){assert.equal(redirects[source].destination,'/admin/');assert.equal(redirects[source].permanent,false)}});
test('auth boot and staff guard are mandatory',async()=>{const [js,api]=await Promise.all([read('admin/admin.js'),read('admin/admin-api.js')]);assert.match(api,/signInWithPassword/);assert.match(api,/rpc\('is_staff'\)/);assert.match(js,/await api\.isStaff\(\)/);assert.match(js,/await api\.logout\(\)/)});
test('workflow separates active/history and supports terminal corrections',()=>{const rows=['new','accepted','preparing','ready','collected','cancelled','returned','refunded'].map((status,id)=>({id,status,created_at:new Date(Date.now()-90000000).toISOString()}));assert.deepEqual(filterOrders(rows,'active').map(x=>x.status),['new','accepted','preparing','ready']);assert.deepEqual(filterOrders(rows,'history').map(x=>x.status),['collected','cancelled','returned','refunded']);assert.deepEqual(nextAction('ready'),['collected','Wydaj']);assert.deepEqual(historyAction('collected'),['returned','Oznacz zwrot']);assert.deepEqual(historyAction('returned'),['refunded','Oznacz refundację']);assert.equal(isStale(rows[0]),true)});
test('storage adapter uploads, exposes public URL and removes safe paths',async()=>{const calls=[];const bucket={upload:async(path,file,options)=>{calls.push(['upload',path,file,options]);return{error:null}},getPublicUrl:path=>({data:{publicUrl:`https://x.test/storage/v1/object/public/menu-images/${path}`}}),remove:async paths=>{calls.push(['remove',paths]);return{error:null}}};const adapter=createStorageAdapter({storage:{from:name=>{assert.equal(name,'menu-images');return bucket}}});const result=await adapter.upload(new Blob(['x'],{type:'image/png'}));assert.match(result.path,/^products\/\d{4}\/\d{2}\/[0-9a-f-]+\.png$/);assert.equal(storagePathFromUrl(result.url),result.path);await adapter.remove(result.path);assert.equal(calls[0][0],'upload');assert.equal(calls[1][0],'remove')});
test('baseline covers production objects missing from migrations',async()=>{const sql=await read('supabase/baseline/production_schema_20260930.sql');for(const name of ['customers','collections','menu_categories','menu_products'])assert.match(sql,new RegExp(`create table public\\.${name}`));assert.match(sql,/NEVER APPLY TO THE EXISTING PRODUCTION PROJECT/)});
