import {chromium,webkit} from 'playwright';

const arg=process.argv.find(value=>value.startsWith('--base-url='));
const baseUrl=(arg?.split('=').slice(1).join('=')||process.env.ADMIN_BASE_URL||'http://127.0.0.1:4173').replace(/\/$/,'');
const shareArg=process.argv.find(value=>value.startsWith('--vercel-share='));
const shareToken=shareArg?.split('=').slice(1).join('=')||process.env.VERCEL_SHARE_TOKEN||null;
const credentials=process.env.ADMIN_TEST_EMAIL&&process.env.ADMIN_TEST_PASSWORD?{email:process.env.ADMIN_TEST_EMAIL,password:process.env.ADMIN_TEST_PASSWORD}:null;
const projects=[['chromium-desktop',chromium,{viewport:{width:1280,height:800}}],['chromium-mobile',chromium,{viewport:{width:390,height:844},isMobile:true,hasTouch:true}]];
if(process.env.ADMIN_E2E_WEBKIT==='1'||process.argv.includes('--webkit'))projects.push(['webkit-mobile',webkit,{viewport:{width:390,height:844},isMobile:true,hasTouch:true}]);
let failed=false;
for(const[name,browserType,contextOptions]of projects){let browser;try{browser=await browserType.launch({headless:true});const context=await browser.newContext(contextOptions);const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));const adminUrl=shareToken?`${baseUrl}/admin/?_vercel_share=${encodeURIComponent(shareToken)}`:`${baseUrl}/admin/`;await page.goto(adminUrl,{waitUntil:'domcontentloaded',timeout:30000});const email=page.locator('#email'),password=page.locator('#password');await email.click();await email.fill('focus.test@example.com');if(await email.inputValue()!=='focus.test@example.com'||await email.evaluate(el=>document.activeElement===el)!==true)throw new Error('email input lost focus/value');await password.click();await password.fill('temporary-input-check');if(await password.inputValue()!=='temporary-input-check'||await password.evaluate(el=>document.activeElement===el)!==true)throw new Error('password input lost focus/value');if(credentials){await email.fill(credentials.email);await password.fill(credentials.password);await Promise.all([page.waitForResponse(r=>r.url().includes('/auth/v1/token')&&r.request().method()==='POST'),page.locator('#loginBtn').click()]);await page.locator('#adminView:not(.hidden)').waitFor();for(const view of ['orders','flavours','catalog','announcements']){await page.locator(`#adminNav [data-view="${view}"]`).click();await page.locator(`#${view}View:not(.hidden)`).waitFor()}await page.locator('#logoutBtn').click();await page.locator('#authView:not(.hidden)').waitFor()}else if(name==='chromium-desktop'){await Promise.all([page.waitForResponse(r=>r.url().includes('/auth/v1/token')&&r.request().method()==='POST'),page.locator('#loginBtn').click()]);await page.locator('#authMessage.error').waitFor()}if(errors.length)throw new Error(errors.join('; '));console.log(`${name}: PASS${credentials?' authenticated':name==='chromium-desktop'?' inputs + auth request':' inputs-only'}`);await context.close()}catch(error){failed=true;console.error(`${name}: FAIL: ${error.message}`)}finally{await browser?.close()}}
if(!credentials)console.log('Authenticated E2E skipped: ADMIN_TEST_EMAIL/PASSWORD are unavailable.');
if(failed)process.exitCode=1;
