create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  public_token uuid not null default gen_random_uuid() unique,
  order_number bigint generated by default as identity unique,
  status text not null default 'new' check (status in ('new','accepted','preparing','ready','collected','cancelled')),
  locale text not null default 'pl' check (locale in ('pl','de','en','cs')),
  customer_name text,
  total numeric(10,2) not null default 0 check (total >= 0),
  estimated_minutes integer not null default 15 check (estimated_minutes between 0 and 180),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_key text not null,
  name text not null,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 20),
  created_at timestamptz not null default now()
);

create index if not exists orders_status_created_at_idx on public.orders(status, created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.create_pickup_order(
  p_items jsonb,
  p_locale text default 'pl'
)
returns table (
  order_id bigint,
  public_token uuid,
  order_number bigint,
  status text,
  estimated_minutes integer,
  total numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id bigint;
  v_total numeric(10,2) := 0;
  v_count integer;
  v_item jsonb;
  v_name text;
  v_key text;
  v_price numeric(10,2);
  v_qty integer;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'items must be an array';
  end if;

  v_count := jsonb_array_length(p_items);
  if v_count < 1 or v_count > 50 then
    raise exception 'invalid item count';
  end if;

  if p_locale not in ('pl','de','en','cs') then
    p_locale := 'pl';
  end if;

  insert into public.orders(locale)
  values (p_locale)
  returning id into v_order_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_key := left(coalesce(v_item->>'key','item'), 120);
    v_name := left(coalesce(v_item->>'name',''), 200);
    v_price := coalesce((v_item->>'price')::numeric, 0);
    v_qty := coalesce((v_item->>'qty')::integer, 1);

    if v_name = '' or v_price < 0 or v_price > 1000 or v_qty < 1 or v_qty > 20 then
      raise exception 'invalid order item';
    end if;

    insert into public.order_items(order_id, product_key, name, unit_price, quantity)
    values (v_order_id, v_key, v_name, v_price, v_qty);

    v_total := v_total + (v_price * v_qty);
  end loop;

  update public.orders set total = v_total where id = v_order_id;

  return query
  select o.id, o.public_token, o.order_number, o.status, o.estimated_minutes, o.total
  from public.orders o
  where o.id = v_order_id;
end;
$$;

create or replace function public.get_pickup_order_status(p_public_token uuid)
returns table (
  order_number bigint,
  status text,
  estimated_minutes integer,
  total numeric,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select o.order_number, o.status, o.estimated_minutes, o.total, o.created_at, o.updated_at
  from public.orders o
  where o.public_token = p_public_token
  limit 1;
$$;

revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
grant execute on function public.create_pickup_order(jsonb, text) to anon, authenticated;
grant execute on function public.get_pickup_order_status(uuid) to anon, authenticated;
