create table if not exists public.order_reviews (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  locale text not null default 'pl' check (locale in ('pl','de','en','cs')),
  created_at timestamptz not null default now()
);

alter table public.order_reviews enable row level security;
revoke all on public.order_reviews from anon, authenticated;

create or replace function public.submit_pickup_order_review(
  p_public_token uuid,
  p_rating integer,
  p_comment text default null,
  p_locale text default 'pl'
)
returns table (
  rating integer,
  comment text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id bigint;
begin
  if p_rating < 1 or p_rating > 5 then
    raise exception 'invalid rating';
  end if;

  if p_locale not in ('pl','de','en','cs') then
    p_locale := 'pl';
  end if;

  select o.id
    into v_order_id
  from public.orders o
  where o.public_token = p_public_token
    and o.status in ('ready','collected')
  limit 1;

  if v_order_id is null then
    raise exception 'order not eligible';
  end if;

  insert into public.order_reviews(order_id, rating, comment, locale)
  values (
    v_order_id,
    p_rating,
    nullif(left(trim(coalesce(p_comment, '')), 1000), ''),
    p_locale
  )
  on conflict (order_id) do update
    set rating = excluded.rating,
        comment = excluded.comment,
        locale = excluded.locale
  returning order_reviews.rating,
            order_reviews.comment,
            order_reviews.created_at
  into rating, comment, created_at;

  return next;
end;
$$;

revoke all on function public.submit_pickup_order_review(uuid, integer, text, text) from public;
grant execute on function public.submit_pickup_order_review(uuid, integer, text, text) to anon, authenticated;

drop function if exists public.get_pickup_order_status(uuid);

create function public.get_pickup_order_status(p_public_token uuid)
returns table(
  order_number bigint,
  status text,
  estimated_minutes integer,
  ready_at timestamptz,
  total numeric,
  created_at timestamptz,
  updated_at timestamptz,
  has_review boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    o.order_number,
    o.status,
    o.estimated_minutes,
    o.ready_at,
    o.total,
    o.created_at,
    o.updated_at,
    exists(
      select 1
      from public.order_reviews r
      where r.order_id = o.id
    ) as has_review
  from public.orders o
  where o.public_token = p_public_token
  limit 1;
$$;

revoke all on function public.get_pickup_order_status(uuid) from public;
grant execute on function public.get_pickup_order_status(uuid) to anon, authenticated;
